<?php
require_once 'config.php';

if (!isAdmin()) {
    header('Location: login.php');
    exit;
}

// Fetch all closed tickets with user details
$sql = "SELECT t.*, u.username FROM tickets t JOIN users u ON t.user_id = u.id WHERE LOWER(t.status) = 'closed' ORDER BY t.created_at DESC";
$stmt = $pdo->query($sql);
$tickets = $stmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Closed Tickets Report - <?php echo date('Y-m-d'); ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        @media print {
            .no-print { display: none !important; }
            body { background: white; padding: 0; }
            .container { width: 100%; max-width: 100%; margin: 0; }
            .shadow-sm { box-shadow: none !important; }
            .table td, .table th { font-size: 12px; }
        }
        .report-header { border-bottom: 3px solid #1e3a8a; margin-bottom: 30px; padding-bottom: 10px; }
        /* Adjusted for better fitting on standard paper */
        .ticket-img { max-width: 150px; height: auto; border-radius: 5px; border: 1px solid #ddd; margin-bottom: 5px; }
        .download-btn { font-size: 0.75rem; padding: 2px 8px; }
    </style>
</head>
<body class="bg-light">

<div class="container my-5">
    <div class="no-print mb-4 d-flex justify-content-between">
        <a href="dashboard.php" class="btn btn-secondary text-white">← Back to Dashboard</a>
        <button onclick="window.print()" class="btn btn-primary">
            <i class="fas fa-file-pdf me-2"></i>Print Report / Save as PDF
        </button>
    </div>

    <div class="bg-white p-5 shadow-sm rounded">
        <div class="report-header d-flex justify-content-between align-items-center">
            <div>
                <h1 class="text-primary fw-bold">Ticket System Report</h1>
                <p class="text-muted">Summary of Resolved (Closed) Tickets</p>
            </div>
            <div class="text-end">
                <p class="mb-0"><strong>Date:</strong> <?php echo date('F j, Y'); ?></p>
                <p class="mb-0"><strong>Admin:</strong> <?php echo htmlspecialchars($_SESSION['username']); ?></p>
            </div>
        </div>

        <table class="table table-bordered align-middle">
            <thead class="table-dark">
                <tr>
                    <th width="8%">ID</th>
                    <th width="20%">User & Subject</th>
                    <th width="37%">Reason / Description</th>
                    <th width="35%">Attached Evidence</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tickets as $ticket): ?>
                <tr>
                    <td class="text-center fw-bold">#<?php echo $ticket['id']; ?></td>
                    <td>
                        <strong><?php echo htmlspecialchars($ticket['username']); ?></strong><br>
                        <small class="text-info"><?php echo htmlspecialchars($ticket['subject']); ?></small>
                    </td>
                    <td><div style="max-height: 150px; overflow: hidden;"><?php echo nl2br(htmlspecialchars($ticket['description'])); ?></div></td>
                    <td class="text-center">
                        <?php 
                        // Auto-detect common column names for images
                        $file = $ticket['attachment'] ?? $ticket['image'] ?? $ticket['ticket_img'] ?? null;
                        $filePath = "uploads/" . $file;

                        if ($file && file_exists($filePath)): ?>
                            <div class="d-inline-block p-1 border rounded bg-light">
                                <img src="<?php echo $filePath; ?>" class="ticket-img d-block" alt="Ticket Image">
                                
                                <div class="no-print mt-1">
                                    <a href="<?php echo $filePath; ?>" download="Ticket_#<?php echo $ticket['id']; ?>_Image" class="btn btn-success btn-sm download-btn">
                                        <i class="fas fa-download"></i> Download
                                    </a>
                                </div>
                            </div>
                        <?php else: ?>
                            <span class="text-muted small italic">No image provided</span>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
        <div class="mt-4 text-center text-muted small border-top pt-3">
            Generated by Office Ticket System &copy; <?php echo date('Y'); ?>
        </div>
    </div>
</div>

</body>
</html>